name: Ideias com azeite
description: Temperando bem o seu código
author: Rafael Miceli
markdown: kramdown

# Please remove or change to your own from http://disqus.com/
disqus_shortname: rafaelmiceli

navigation:
- text: Home
  url: /
  icon: "glyphicon glyphicon-home"
- text: Sobre
  url: /about.html

paginate: 10

# Scheme and Hostname for your website without trailing slash
url: http://rafael-miceli.github.io

# Folder part of the path to get to your website without trailing slash
# (ex: /projectname)
baseurl: 

# Code for Google Analytics
gacode: UA-XXXXX-X

githuburl: https://github.com/Rafael-Miceli/rafael-miceli.github.com

safe: true
